### PR TITLE
add anchor to navbar

### PR DESCRIPTION
**Pull request by jeffjxu**

### CODE REVIEW

**Review by anish-krishnan — CHANGES_REQUESTED** [review]
Hey I did a clean install of this branch, ran `npm install` and `npm start` and got this error. Am I not installing correctly?

```
./src/LandingPage/Landing.js
  Line 11:  'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 12:  'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 13:  'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 14:  'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 15:  'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 16:  'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 17:  'React' must be in scope when using JSX  react/react-in-jsx-scope

Search for the keywords to learn more about each error.
```

**Comment by jeffjxu** [comment]
I'm not sure, it's working correctly for me. This branch is also not ready since Brandyn is working on making the waitlist button appear based on scroll distance on this branch

**Comment by jeffjxu** [comment]
Maybe try running npm ci?

**Review by anish-krishnan — APPROVED** [review]
Okay this must be an issue on my end. Looks great otherwise!

**Pull request merged**
